<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE products [
        <!ELEMENT products (product)*>
        <!ELEMENT product (name|price)*>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT price (#PCDATA)>
        ]>
<products>
    <product>
        <name>Guitar</name>
        <price>1000</price>
    </product>
    <product>
        <name>Flute</name>
        <price>500</price>
    </product>
</products>